### PR TITLE
Update templates of first and second renewal email reminders

### PR DESCRIPTION
**Pull request by cintamani**
From: https://eaflood.atlassian.net/browse/RUBY-1019

This update the template of the first and second email reminders to match the magic link template. In the new template, we don't have differences for those email templates. Little refactoring has been done there, as it is quite possible that the email templates will differ again in the near future.

Screenshot 2020-05-15 at 14 31 41

### CODE REVIEW

**Comment by irisfaraway** [comment]
@cintamani Should this be behind a feature flag? I thought there might be a possibility of us shipping reminders before the magic link renewal was ready.

**Comment by cintamani** [comment]
@irisfaraway this is already behind a feature flag: https://github.com/DEFRA/waste-carriers-back-office/blob/master/lib/tasks/email.rake#L13

**Comment by irisfaraway** [comment]
@cintamani Sending reminders at all is behind a feature flag, yeah. But I meant a flag for sending reminders vs sending out the magic link. Since it looks like this overrides the previous version of the reminder email entirely.

**Comment by irisfaraway** [comment]
Ignore me, I missed a conversation at some point and this is not an issue!

**Pull request merged**
